### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Rawanyoussef**
implemented two key functions for the Text Analyzer project:

A function to count the number of words in the text, excluding punctuation. A function to count the number of sentences in the text.

### CODE REVIEW

**Comment by Rawanyoussef** [comment]
implemented two key functions for the Text Analyzer project:

A function to count the number of words in the text, excluding punctuation.
A function to count the number of sentences in the text.

**Comment by Rawanyoussef** [comment]
A function to count the number of words in the text, excluding punctuation.
A function to count the number of sentences in the text.

**Comment by Rawanyoussef** [comment]
هاي

**Comment by RawanElOlemy** [comment]
باي

**Pull request merged**
